services:
  mongo-db:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - 'mongo_db:/data/db'
    networks:
      - book-store