services:
  postgres-db:
    image: 'postgres:14'
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=root'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_db:/var/lib/postgresql/data'
    networks:
      - book-store